// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../closure-templates/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJs', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri', 'soydata.VERY_UNSAFE'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.soy.data.SanitizedContentKind', 'goog.string', 'goog.string.StringBuffer'], false);
goog.addDependency('../../../paper-library/paper/paper.soy.js', ['paper'], ['soy', 'soydata'], false);
goog.addDependency('../../../paper-library/paper/toast.js', ['paper.Toast'], ['goog.dom.classlist', 'goog.soy', 'goog.ui.Control', 'goog.ui.ControlRenderer', 'paper'], true);
goog.addDependency('../../../paper-library/paper/toast_test.js', ['paper.ToastTest'], ['goog.dom', 'goog.dom.classlist', 'goog.soy', 'goog.testing.testSuite', 'paper', 'paper.Toast'], true);
