// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../closure-templates/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJs', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri', 'soydata.VERY_UNSAFE'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.soy.data.SanitizedContentKind', 'goog.string', 'goog.string.StringBuffer'], false);
goog.addDependency('../../../proton-library/pt/events/taphandler.js', ['pt.events.TapHandler'], ['goog.events', 'goog.events.EventTarget'], false);
goog.addDependency('../../../proton-library/pt/navigation/endpoint.js', ['pt.navigation.Endpoint'], [], false);
goog.addDependency('../../../proton-library/pt/navigation/navigation.js', ['pt.navigation'], [], false);
goog.addDependency('../../../proton-library/pt/navigation/navigationrequest.js', ['pt.navigation.Event', 'pt.navigation.NavigationRequest', 'pt.navigation.NavigationRequestState'], [], false);
goog.addDependency('../../../proton-library/pt/navigation/navigator.js', ['pt.navigation.Navigator'], ['goog.events', 'pt.navigation.NavigationRequest'], false);
goog.addDependency('../../../proton-library/pt/navigation/pageendpoint.js', ['pt.navigation.PageEndpoint'], [], false);
goog.addDependency('../../../proton-library/pt/navigation/route.js', ['pt.navigation.Route'], [], false);
goog.addDependency('../../../proton-library/pt/navigation/routes.js', ['pt.navigation.Routes'], [], false);
goog.addDependency('../../../proton-library/pt/navigation/urlendpoint.js', ['pt.navigation.UrlEndpoint'], [], false);
goog.addDependency('../../../proton-library/pt/number/number.js', ['pt.number'], [], false);
goog.addDependency('../../../proton-library/pt/ui/carousel.js', ['pt.ui.Carousel'], ['goog.Timer', 'goog.array', 'goog.dom.classlist', 'goog.ui.Component'], false);
goog.addDependency('../../../proton-library/pt/ui/component.js', ['pt.ui.Component'], ['goog.object', 'goog.ui.Component'], false);
goog.addDependency('../../../proton-library/pt/ui/control.js', ['pt.ui.Control'], ['goog.ui.Control', 'goog.ui.ControlRenderer'], false);
goog.addDependency('../../../proton-library/pt/ui/fastclick.js', ['pt.ui.FastClick'], [], false);
goog.addDependency('../../../proton-library/pt/ui/menu.js', ['pt.ui.Menu'], ['goog.ui.ContainerRenderer', 'goog.ui.Menu', 'goog.ui.MenuRenderer'], false);
goog.addDependency('../../../proton-library/pt/ui/page.js', ['pt.ui.Page'], ['goog.ui.Container'], true);
goog.addDependency('../../../proton-library/pt/ui/selectable.js', ['pt.ui.Selectable'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.events.EventType'], false);
goog.addDependency('../../../proton-library/pt/ui/tab.js', ['pt.ui.Tab'], ['goog.ui.ControlRenderer', 'goog.ui.Tab'], false);
goog.addDependency('../../../proton-library/pt/ui/tabs.js', ['pt.ui.Tabs'], ['goog.ui.ContainerRenderer', 'goog.ui.TabBar', 'goog.ui.TabBarRenderer'], false);
goog.addDependency('../../../proton-library/pt/ui/tabview.js', ['pt.ui.TabView'], ['goog.ui.Component'], false);
